import type { Metadata } from "next";
import "./globals.css";
import AdBar from "@/components/navigation/AdBar";
import Navbar from "@/components/navigation/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
            
            {/* Main content */}
            <div className="flex flex-col flex-1 "> {/* Add margin on medium screens to account for the visible sidebar */}
              <AdBar />
              <Navbar />
              <main className="flex-1 p-4">
                {children}
              </main>
            </div>
         
      </body>
    </html>
  );
}